### PR TITLE
add new class's on the existing project

### PR DESCRIPTION
**Pull request by HermelaDemeke**
The Person class is a basic class that implements the Nameable interface, providing methods to get and set a person's name, age, and whether they have parental permission. It also includes a method to check if the person is of age to use certain services. Additionally, there's a method to get the person's correct name, and the default implementation simply returns the person's name.

The Decorator class is an abstract class that also implements the Nameable interface and takes another Nameable object in its constructor. It provides a method to get the correct name, which is ultimately delegated to the wrapped Nameable object.

The CapitalizeDecorator and TrimmerDecorator classes are concrete decorator classes that extend the Decorator class. They modify the behavior of the getCorrectName method defined in the Nameable interface. The CapitalizeDecorator capitalizes the name, while the TrimmerDecorator trims the name if it exceeds a certain length.

The Student and Teacher classes extend the Person class, adding additional attributes specific to students and teachers, respectively. The Teacher class also overrides the canUseServices method to always return true, indicating that teachers can use services without age or parental permission restrictions.

Finally, the Main class contains the main method where instances of Person, CapitalizeDecorator, and TrimmerDecorator are created and their correct names are printed to the console.

### CODE REVIEW

**Review by Benawi — CHANGES_REQUESTED** [review]
Hi 👋 @HermelaDemeke  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

  - Teacher and student classes are missed in this branch
 
giphy

Your Code Review Request will be marked as invalid, so please submit a new one once you are ready 🙏


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @benawi in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Benawi** [comment]
Hi 👋 @HermelaDemeke 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

 - You have submitted a project, that has a branch conflict

image
giphy

Your Code Review Request will be marked as invalid, so please submit a new one once you are ready 🙏


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @benawi in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Benawi — APPROVED** [review]
Hi, @HermelaDemeke 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
✅ Correct use of Gitflow
✅ Create a class ` Nameable` --- Interface
✅ `Person ` class inherits from `Nameable`
✅ Create `Decorator ` and inherits from `Nameable`.
✅ Create ` CapitalizeDecorator ` and ` TrimmerDecorator`


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @benawi in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by HermelaDemeke** [comment]
add new class's on the existing project by HermelaDemeke · Pull Request #4
· HermelaDemeke/project1 (github.com)
<https://github.com/HermelaDemeke/project1/pull/4> please check it out
there is no merge conflict

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Review by Benawi — APPROVED** [review]
Hi 👋 @HermelaDemeke 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a branch conflict

image
giphy

Your Code Review Request will be marked as invalid, so please submit a new one once you are ready 🙏


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @benawi in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
